{
    "id": "errors",
    "name": "The Cat And The Mouse",
    "objective": "Learn how to catch and handle errors with Promises",
    "resources": {
        "content": "lesson.md",
        "code": "code.txt",
        "animation": "animation.html"
    },
    "editor": {
        "editableArea": {
            "start": 21,
            "end": 26
        },
        "completers": [
            {
                "value": "catch",
                "score": 1,
                "meta": "catch keyword"
            },
            {
                "value": "try",
                "score": 1,
                "meta": "try keyword"
            },
            {
                "value": "await",
                "score": 1,
                "meta": "Waits for a Promise"
            },
            {
                "value": "runToMouse",
                "score": 1,
                "meta": "Promise"
            },
            {
                "value": "catchMouse",
                "score": 1,
                "meta": "Promise"
            },
            {
                "value": "cry",
                "score": 1,
                "meta": "function"
            },
            {
                "value": "error",
                "score": 1,
                "meta": "Caught error"
            }
        ]
    },
    "test": {
        "script": "test.js",
        "allowlist": ["await", "catch", "try", "runToMouse", "catchMouse", "cry", "Escaped", "error", "then", "function"]
    },
    "runner": {
        "script": "runner.js",
        "timeout": 5000
    },
    "feedback": [
        {
            "events": ["runToMouse", "finished;runToMouse", "catchMouse", "finished;catchMouse", "cry", "finished;cry", "finished"],
            "result": {
                "success": true,
                "message": "Congrats! You handled the mouse escaping from the cat correctly."
            }
        },
        {
            "events": ["catchMouse", "finished;catchMouse", "cry", "finished;cry", "finished"],
            "result": {
                "success": true,
                "message": "Congrats! You handled the mouse escaping from the cat correctly. (The cat could've tried running to the mouse first though)"
            }
        },
        {
            "events": ["catchMouse", "finished;catchMouse"],
            "result": {
                "success": false,
                "message": "The mouse escaped but the cat didn't stop and cry.\nAdd code to the catch block to handle any errors, and make sure to use await with Promises."
            }
        },
        {
            "events": ["runToMouse", "finished;runToMouse", "catchMouse", "finished;catchMouse"],
            "result": {
                "success": false,
                "message": "The mouse escaped but the cat didn't stop and cry.\nAdd code to the catch block to handle any errors, and make sure to use await with Promises."
            }
        },
        {
            "events": ["runToMouse", "catchMouse", "finished;catchMouse", "cry", "finished;cry", "finished"],
            "result": {
                "success": false,
                "message": "The cat should finish running to the mouse before trying to catch it. Try again using the await keyword."
            }
        },
        {
            "events": [["runToMouse", "catchMouse"], "finished;catchMouse", "finished;runToMouse"],
            "result": {
                "success": false,
                "message": "The cat should finish running to the mouse before trying to catch it. Try again using the await keyword."
            }
        },
        {
            "events": ["runToMouse", "finished;runToMouse"],
            "result": {
                "success": false,
                "message": "You didn't try to catch the mouse. Try again using the catchMouse function. Remember to catch any errors!"
            }
        }
    ]
}